AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  JornageoRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: jornageo-registration
      CodeUri: jornageo-registration/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 3
      MemorySize: 128
      Role: arn:aws:iam::248189947068:role/jornageo-lambda-role
      Environment:
        Variables:
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:248189947068:jornageo
          DYNAMODB_TABLE: jornageo-registrations
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
