version: 0.2

env:
  variables:
    S3_BUCKET: "jornageo.dataiesb.com"
    CLOUDFRONT_DISTRIBUTION_ID: "E1N9FUZGW0SICT"

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Syncing website files to S3...
      - aws s3 sync . s3://$S3_BUCKET --exclude "*.tf" --exclude "*.zip" --exclude ".git/*" --exclude "*.py" --exclude "*.yml" --exclude "*.yaml" --exclude "*.sh" --exclude ".terraform/*" --exclude "buildspec.yml" --exclude "infrastructure.yaml" --exclude "deploy.sh" --exclude "create_tables.py" --exclude "lambda_function.py"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  name: jornageo-website
